# Optimized Cloud Build - Using Flutter Docker Image
steps:
  # Build Flutter web app using pre-built Flutter container
  - name: 'ghcr.io/cirruslabs/flutter:stable'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        flutter --version
        flutter pub get
        flutter build web --release

  # Deploy to Firebase using gcloud (which has firebase integration)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Firebase CLI
        curl -sL https://firebase.tools | bash
        
        # Deploy using service account authentication
        firebase deploy --only hosting --project fitness-tracker-8d0ae

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: '900s'