# Final Working Cloud Build - Staging Pipeline
steps:
  # Install Flutter in a container with git
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/flutter/flutter.git', '-b', 'stable', '--depth', '1']

  # Setup and build Flutter app
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        # Install necessary packages
        apt-get update
        apt-get install -y curl git unzip xz-utils zip libglu1-mesa
        
        # Set Flutter path
        export PATH="/workspace/flutter/bin:$$PATH"
        
        # Configure git (required for Flutter)
        git config --global --add safe.directory /workspace/flutter
        
        # Flutter setup
        flutter --version
        flutter config --no-analytics
        flutter pub get
        flutter build web --release

  # Deploy to Firebase
  - name: 'gcr.io/andreysenov/firebase'
    args: ['deploy', '--only', 'hosting', '--project', 'fitness-tracker-8d0ae']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
timeout: '1800s'