# Optimized Cloud Build - Web and Android
steps:
  # Build Flutter web and Android apps
  - name: 'ghcr.io/cirruslabs/flutter:stable'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        flutter --version
        flutter pub get
        
        # Download keystore for release signing
        gsutil cp gs://fitness-tracker-8d0ae_cloudbuild/keystore/upload-keystore.jks android/app/
        
        # Create key.properties for release signing
        cat > android/key.properties << EOF
        storePassword=Sanvtv97!@
        keyPassword=Sanvtv97!@
        keyAlias=upload
        storeFile=upload-keystore.jks
        EOF
        
        # Build web app
        flutter build web --release
        
        # Build Android APK (release)
        flutter build apk --release

  # Deploy web to Firebase and store Android artifacts
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Firebase CLI
        npm install -g firebase-tools
        
        # Deploy web app using service account authentication
        firebase deploy --only hosting --project fitness-tracker-8d0ae

artifacts:
  objects:
    location: 'gs://fitness-tracker-8d0ae_cloudbuild/artifacts'
    paths:
      - 'build/app/outputs/flutter-apk/app-release.apk'

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: '1800s'