# Working Cloud Build - Staging Pipeline
steps:
  # Install Flutter
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/flutter/flutter.git', '-b', 'stable', '--depth', '1']

  # Get Flutter dependencies
  - name: 'ubuntu'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        export PATH="/workspace/flutter/bin:$$PATH"
        flutter --version
        flutter pub get

  # Build web app
  - name: 'ubuntu'  
    entrypoint: 'bash'
    args:
      - '-c' 
      - |
        export PATH="/workspace/flutter/bin:$$PATH"
        flutter build web --release

  # Deploy to Firebase
  - name: 'gcr.io/andreysenov/firebase'
    args: ['deploy', '--only', 'hosting', '--project', 'fitness-tracker-8d0ae']

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: '1200s'