# Optimized Cloud Build - Web and Android
steps:
  # Build Flutter web and Android apps
  - name: 'ghcr.io/cirruslabs/flutter:stable'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        flutter --version
        flutter pub get
        
        # Build web app
        flutter build web --release
        
        # Build Android APK
        flutter build apk --release

  # Deploy web to Firebase and store Android artifacts
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Firebase CLI
        npm install -g firebase-tools
        
        # Deploy web app using service account authentication
        firebase deploy --only hosting --project fitness-tracker-8d0ae

artifacts:
  objects:
    location: 'gs://fitness-tracker-8d0ae_cloudbuild/artifacts'
    paths:
      - 'build/app/outputs/flutter-apk/*.apk'

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: '1800s'