name: Staging Deploy

on:
  push:
    branches:
      - develop  # Trigger on push to develop branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6'
        channel: 'stable'
        
    - name: Setup Node.js for Firebase
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Decode staging google-services.json
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_STAGING }}" | base64 -d > android/app/google-services.json
        
    - name: Configure Google Client ID for staging
      run: |
        sed -i 's/{{GOOGLE_CLIENT_ID}}/${{ secrets.GOOGLE_CLIENT_ID_STAGING }}/g' web/index.html
        cat web/index.html | grep google-signin-client_id
      
    - name: Run tests
      run: flutter test
      
    - name: Build Flutter Web (Staging)
      run: flutter build web --release --dart-define=ENVIRONMENT=staging
      
    - name: Deploy to Firebase Hosting (Staging)
      run: |
        firebase use fitness-tracker-8d0ae --token "${{ secrets.FIREBASE_TOKEN }}"
        firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
        
    - name: Setup Java for Android
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Build Debug APK (Staging)
      run: flutter build apk --debug
      
    - name: Upload web artifact
      uses: actions/upload-artifact@v4
      with:
        name: staging-web-build
        path: build/web/
        
    - name: Upload Debug APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: staging-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk