name: Preview Deploy (Feature Branches)

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read
  pull-requests: write  # Required for commenting on PRs
  actions: read
  checks: read

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6'
        channel: 'stable'
        
    - name: Setup Node.js for Firebase
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
      
    - name: Build Flutter Web (Preview)
      run: flutter build web --release --dart-define=ENVIRONMENT=development
      
    - name: Deploy to Firebase Hosting (Preview Channel)
      run: |
        firebase use fitness-tracker-8d0ae --token "${{ secrets.FIREBASE_TOKEN }}"
        firebase hosting:channel:deploy preview-${{ github.ref_name }} --token "${{ secrets.FIREBASE_TOKEN }}"
        
    - name: Comment Preview URL on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 **Preview deployed!**\n\n📱 **Web Preview**: https://fitness-tracker-8d0ae--preview-${{ github.ref_name }}.web.app\n\n*This preview will be available for 7 days.*'
          })